import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "@/components/Footer";
import Banner from "@/components/Banner";
import MarqueeBanner from "@/components/MarqueeBanner";
import AppProviders from "@/components/AppProviders"; // Import your client wrapper here
import Head from "next/head"; // Import Next.js Head component to modify the head of the document

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DealYouDirty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add the external script here */}
        <script
          type="text/javascript"
          src="https://assets.mycartpanda.com/cartx-ecomm-ui-assets/js/cpsales.js"
          async
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MarqueeBanner />
        <AppProviders>
          <Header />
          <Banner />
          {children} {/* Render dynamic content for each page */}
          <Footer />
        </AppProviders>
      </body>
    </html>
  );
}
